name: Generate
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate
        run: |
          cd scripts
          python3 validate.py
          
      - name: Amalgamate
        run: |
          cd scripts
          python3 amalgamate.py
      
      - name: Remove Old
        if: github.ref == 'refs/heads/master'
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        if: github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest 
          body: ${{ github.event.head_commit.message }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            out/db.json
            out/db_minify.json
