name: Generate

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3
          sudo pip3 install jsonschema
      # Runs a single command using the runners shell
      - name: validate
        run: |
          cd scripts
          python3 validate.py

      # Runs a set of commands using the runners shell
      - name: amalgamate
        run: |
          cd scripts
          python3 amalgamate.py
          cd ..
          ls out
          
      - name: Upload db.json
        if: ${{ !contains( github.event_name, 'pull_request' ) }}
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: db
          path: out/db.json
                out/db_minify.json
        
